### ISSUE TITLE
IntranetUserJS: Checkout report link

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/koha-plugin-intranetjs-checkout-report-link#2]
IntranetUserJS: Checkout report link

Linkki lainatilastoraporttiin tietueen pääsivulla G1109. Lisää Määrittely-osioon käytettävän raportin numero.

Testaus:

Poista käytöstä rimpsu // Linkki lainatilastoraporttiin tietueen pääsivulla intranetUserJS-asetuksesta
Määrittele pluginiin lainatilastoraportin numero
Aktivoi plugin
Tarkasta, että tietueen pääsivulle ilmestyy linkki lainatilastoraporttiin ja että linkki toimii

**Comment by lmstrand** [comment]
Seuranta kimpoista, jotka ovat poistaneet rimpsun intranetUserJS:stä ja aktivoineet/konfiguroineet pluginin. Kommentoi tikettiä, kun asia kunnossa omassa kimpassa.

- [x] Lappi
- [x] OUTI
- [x] Siili
- [x] Vaara
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Lastu
- [x] Vaski

**Comment by pknuuti** [comment]
En löytänyt Vaaran nextillä IntranetUserJS-asetuksista tuota rimpsua. Lisäämällä pluginiin vaadittavan määrityksen raportille numero 842 ja aktivoimalla pluginin, ei toimi oikein. Kun klikkaa tietueessa Lainatilaston raporttilinkkiä, se vie Ohjatun raportin luonnin sivulle, ei raporttiin mihin piti mennä.

**Comment by lmstrand** [comment]
Tuon linkin muoto oli muuttunut uudessa 24-versiossa. Kävin muuttamassa ja oman testini mukaan toimii nyt.

**Comment by lmstrand** [comment]
Jajas vielä on ongelmana jokin syntaksivirhe, pitää korjata.

**Comment by lmstrand** [comment]
Nyt näyttäisi avautuvan oikein raportti.

**Comment by pknuuti** [comment]
Nyt Vaaran nextillä toimii tämä eli kunnossa ja peukutettu.

**Comment by atarnus** [comment]
Outi-nextillä käytössä ja toimii.

**Comment by ReettaSiili** [comment]
Siilin nextillä (ja tuotannossa) käytössä ja toimii.

**Comment by LeenaKinnunen** [comment]
Lapissa plugin nextillä päällä ja toimii.

**Comment by ElinaUotila** [comment]
Kirkes nextillä käytössä ja toimii

**Comment by LastuJanneS** [comment]
Lastussa testattu ja toimii.

**Comment by AnneliO** [comment]
Tämä on kaikilla nyt kuosissa. Suljen tiketin.
